const GET_ALL_GENRES = "GET_ALL_GENRES";
const GET_PLATFORMS = "GET_PLATFORMS"
const POST_GAMES = "POST_GAMES"
const GET_ALL_GAMES = "GET_ALL_GAMES"
const GET_GAME_DETAIL = "GET_GAME_DETAIL"
const GET_GAMES_NAME = "GET_GAMES_NAME"
const GET_GAMES_BY_GENRE = "GET_GAMES_BY_GENRE"
const GET_GAMES_BY_PLATFORM = "GET_GAMES_BY_PLATFORM"
const ORDER_BY_NAME = "ORDER_BY_NAME"
const ORDER_BY_RATING = "ORDER_BY_RATING"

export {GET_ALL_GENRES, GET_PLATFORMS, POST_GAMES, GET_ALL_GAMES, GET_GAME_DETAIL, GET_GAMES_NAME, GET_GAMES_BY_GENRE, GET_GAMES_BY_PLATFORM, ORDER_BY_NAME, ORDER_BY_RATING}