const GET_ALL_GENRES = "GET_ALL_GENRES";
const GET_PLATFORMS = "GET_PLATFORMS"
const POST_GAMES = "POST_GAMES"
const GET_ALL_GAMES = "GET_ALL_GAMES"
const GET_GAME_DETAIL = "GET_GAME_DETAIL"
const GET_GAMES_NAME = "GET_GAMES_NAME"
const GET_GAMES_BY_GENRE = "GET_GAMES_BY_GENRE"
const GET_GAMES_BY_PLATFORM = "GET_GAMES_BY_PLATFORM"
const FILTER_BY_CREATED = "FILTER_BY_CREATED"
const ORDER_BY_NAME_ASC = "ORDER_BY_NAME_ASC"
const ORDER_BY_NAME_DESC = "ORDER_BY_NAME_DESC"
const ORDER_BY_RATING_ASC = "ORDER_BY_RATING_ASC"
const ORDER_BY_RATING_DESC = "ORDER_BY_RATING_DESC"
const FILTER_BY_PLATFORM = "FILTER_BY_PLATFORM"
const FILTER_BY_GENRE = "FILTER_BY_GENRE"
const SEARCH_BY_NAME = "SEARCH_BY_NAME"

export {SEARCH_BY_NAME, GET_ALL_GENRES, GET_PLATFORMS, POST_GAMES, GET_ALL_GAMES, GET_GAME_DETAIL, GET_GAMES_NAME, GET_GAMES_BY_GENRE, GET_GAMES_BY_PLATFORM, FILTER_BY_CREATED, ORDER_BY_NAME_ASC, ORDER_BY_NAME_DESC, ORDER_BY_RATING_ASC, ORDER_BY_RATING_DESC, FILTER_BY_PLATFORM, FILTER_BY_GENRE}